trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Publish ProductService
- task: DotNetCoreCLI@2
  displayName: 'Publish ProductService'
  inputs:
    command: 'publish'
    projects: 'ProductService/ProductService.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/ProductService'

# Publish OrderService
- task: DotNetCoreCLI@2
  displayName: 'Publish OrderService'
  inputs:
    command: 'publish'
    projects: 'OrderService/OrderService.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/OrderService'

# Publish IdentityService
- task: DotNetCoreCLI@2
  displayName: 'Publish IdentityService'
  inputs:
    command: 'publish'
    projects: 'IdentityService/IdentityService.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/IdentityService'
